CCFLAGS=-g -Wall
CCC=g++ 

# Absolute path of the MemoPlayer player src directory
MEMOPLAYER_DIR=~/Devel/workspace/MemoPlayer/src

# Path to the place where compiler should be in the SDK
SDK_DIR=~/Devel/workspace/WidgetSDK/tools/compiler
